receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000 
    database: otel 
    traces_table_name: otel_traces
    ttl: 12h
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

extensions:
  health_check:
  pprof:
  zpages:

service: 
  # extensions: [health_check, pprof, zpages]
  pipelines:
    traces: 
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]